#!/usr/bin/env python3
import time
import sensor
import datetime
import configparser

#updates config file
sensor.get_email_info()

#reads motion_sensor.conf for image location, pin, email_enabled, and email
motion_sensor_conf = r'/etc/motion_sensor.conf'
config = configparser.RawConfigParser()
config.read(motion_sensor_conf)

location = config.get('settings', 'location')
image_location = config.get('settings', 'image_location')
pins_string = config.get('settings', 'pin').split(', ')
pins = []
for number in pins_string:
	number =int(number)
	pins.append(number)

email_enabled = config.get('settings', 'email_enabled')
email_enabled = email_enabled.strip(' ')
email_enabled = email_enabled.lower()
email = config.get('settings', 'email')
image_email = config.get('settings', 'image_email')
subject = "ALERT_MOTION_DETECTED"
message = "Motion detected on " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

#detects motion, if motion is detected, sleep for one hour
while True:
	if sensor.detect_motion(pins) is True:
		image_name = sensor.take_picture(location, image_location)
		sensor.get_email_info()
		if email_enabled == 'on':
			sensor.send_email(email, subject, message)
			sensor.send_email(image_email, 'Image_of_Motion', message, image_name) 
		time.sleep(600)

